// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/8/2025, 5:59:00 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/justi/Downloads/jutellane-Main/jutellane-Main/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/justi/Downloads/jutellane-Main/jutellane-Main/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/justi/Downloads/jutellane-Main/jutellane-Main/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/justi/Downloads/jutellane-Main/jutellane-Main/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/justi/Downloads/jutellane-Main/jutellane-Main/plugins/**/*.{js,ts,mjs}","C:/Users/justi/Downloads/jutellane-Main/jutellane-Main/composables/**/*.{js,ts,mjs}","C:/Users/justi/Downloads/jutellane-Main/jutellane-Main/utils/**/*.{js,ts,mjs}","C:/Users/justi/Downloads/jutellane-Main/jutellane-Main/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/justi/Downloads/jutellane-Main/jutellane-Main/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/justi/Downloads/jutellane-Main/jutellane-Main/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/justi/Downloads/jutellane-Main/jutellane-Main/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;